/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Chat` | `/Chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Complaint` | `/Complaint`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Views` | `/Views`; params?: Router.UnknownInputParams; } | { pathname: `/Components/AddComplaint`; params?: Router.UnknownInputParams; } | { pathname: `/Components/MyStatus`; params?: Router.UnknownInputParams; } | { pathname: `/_contexts/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/_utils/api`; params?: Router.UnknownInputParams; } | { pathname: `/_utils/webFix`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Chat` | `/Chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Complaint` | `/Complaint`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Views` | `/Views`; params?: Router.UnknownOutputParams; } | { pathname: `/Components/AddComplaint`; params?: Router.UnknownOutputParams; } | { pathname: `/Components/MyStatus`; params?: Router.UnknownOutputParams; } | { pathname: `/_contexts/AuthContext`; params?: Router.UnknownOutputParams; } | { pathname: `/_utils/api`; params?: Router.UnknownOutputParams; } | { pathname: `/_utils/webFix`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Chat${`?${string}` | `#${string}` | ''}` | `/Chat${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Complaint${`?${string}` | `#${string}` | ''}` | `/Complaint${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Home${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Profile${`?${string}` | `#${string}` | ''}` | `/Profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Views${`?${string}` | `#${string}` | ''}` | `/Views${`?${string}` | `#${string}` | ''}` | `/Components/AddComplaint${`?${string}` | `#${string}` | ''}` | `/Components/MyStatus${`?${string}` | `#${string}` | ''}` | `/_contexts/AuthContext${`?${string}` | `#${string}` | ''}` | `/_utils/api${`?${string}` | `#${string}` | ''}` | `/_utils/webFix${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Chat` | `/Chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Complaint` | `/Complaint`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Views` | `/Views`; params?: Router.UnknownInputParams; } | { pathname: `/Components/AddComplaint`; params?: Router.UnknownInputParams; } | { pathname: `/Components/MyStatus`; params?: Router.UnknownInputParams; } | { pathname: `/_contexts/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/_utils/api`; params?: Router.UnknownInputParams; } | { pathname: `/_utils/webFix`; params?: Router.UnknownInputParams; };
    }
  }
}
